### ISSUE TITLE
check_test_ran.py requires grep and xsltproc

### ISSUE THREAD

**Issue by traversaro** [ignitionrobotics/ign-gui#198]
## Desired behavior
The `check_test_ran.py` requires grep and xsltproc, that may not be present in some machine (especially Windows), leading to `check_` test failures.

## Implementation suggestion
It seems that other ignition projects use a different version of check_test_ran.py that does not use grep and xsltproc (see https://github.com/ignitionrobotics/ign-math/commits/ign-math6/tools/check_test_ran.py, grep and xsltproc usage removed in https://github.com/ignitionrobotics/ign-math/commit/69d881d51c78929f096791a31f23b87f6032ee88#diff-2d6a060081b4c12efdbe4f12e846ead21821236e834f41885a04e41e884687c2 ). Could it make sense to use the same version here, or instead it is better to stick to the version that uses grep and xsltproc ?

## Additional context
Related to https://github.com/conda-forge/libignition-gui-feedstock/issues/2 .

**Comment by scpeters** [comment]
This is a leftover from osrf/gazebo, which uses the [qtest_to_junit.xslt](https://github.com/osrf/gazebo/blob/gazebo11/tools/qtest_to_junit.xslt) file to translate the xml output files produced by QTest into junit files that can be read by Jenkins. We removed this functionality from other ignition packages, as you noted, but I hadn't removed it here as I thought we were still using QTest. It turns out we stopped using it as of [bitbucket pull request 70](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/70/page/1) (13d314eb2b6a9fc3ebb4ae723bad990546d557aa), so we can remove the `grep` and `xsltproc` portions from `check_test_ran.py` as well.

**Comment by scpeters** [comment]
see #203
