### ISSUE TITLE
World control plugin start_paused

### ISSUE THREAD

**Issue by mohamedsayed18** [ignitionrobotics/ign-gui#87]
`<start_paused>false</start_paused>`. The world starts unpaused for a moment and then pause automatically
Even the value is false.
This happens when running `ign gazebo empty.sdf` or any world.
But it don't happen when testing the gui plugin ign `gui -v 4 -c examples/config/time.config`. so maybe the issue should be moved ign-gazebo repo

**Comment by chapulina** [comment]
I can't reproduce this issue. I'm testing with `ign gui -v 4 -c examples/config/time.config`.

Are you testing with `ign gazebo`? Because in that case, `ign-gazebo` may be the one pausing automatically, overriding this option. In that case, I don't think it would be a bug with this plugin, but it can be misleading.

**Comment by mohamedsayed18** [comment]
Yes, this is my mistake I only tested with ign gazebo.
In that case I'll add the details to the description of the issue and close the pull request.
